import sqlite3 as sl
pathDB='web_interface/Logs.db'
con = sl.connect(pathDB)
with con:
    con.execute("""PRAGMA foreign_keys = ON;""")
    con.execute("""INSERT INTO RULES (rule_id, name, web, setting, control, report, bot) VALUES ('99', 'полный доступ', '1', '1', '1', '1', '1')""")
    con.execute("""INSERT INTO RULES (rule_id, name, web, setting, control, report, bot) VALUES ('0', 'запрет доступа', '0', '0', '0', '0', '0')""")
    con.execute("""INSERT INTO RULES (rule_id, name, web, setting, control, report, bot) VALUES ('10', 'только просмотр', '1', '0', '0', '0', '0')""")
    con.execute("""INSERT INTO RULES (rule_id, name, web, setting, control, report, bot) VALUES ('20', 'с уставками', '1', '1', '0', '0', '0')""")
    con.execute("""INSERT INTO RULES (rule_id, name, web, setting, control, report, bot) VALUES ('30', 'с управлением', '1', '1', '1', '0', '0')""")
    
    con.execute("""INSERT INTO CLIENT (name, rule_id) VALUES ('DEBIT-E', '99')""")
    con.execute("""INSERT INTO CLIENT (name, rule_id) VALUES ('Клиент 1', '0')""")
    con.execute("""INSERT INTO CLIENT (name, rule_id) VALUES ('Клиент 2', '10')""")
    con.execute("""INSERT INTO CLIENT (name, rule_id) VALUES ('Клиент 3', '20')""")
    con.execute("""INSERT INTO CLIENT (name, rule_id) VALUES ('Клиент 4', '30')""")
    
    con.execute("""INSERT INTO USER (client_id, name, login, password) VALUES ('1', 'admin', 'admin', 'qwerty')""")
    con.execute("""INSERT INTO USER (client_id, name, login, password) VALUES ('1', 'сервис инженер', 'serv_eng', '123')""")
    con.execute("""INSERT INTO USER (client_id, name, login, password) VALUES ('2', 'технолог1', 'tech1', '123')""")
    con.execute("""INSERT INTO USER (client_id, name, login, password) VALUES ('2', 'оператор1', 'oper1', '123')""")
    con.execute("""INSERT INTO USER (client_id, name, login, password) VALUES ('3', 'технолог2', 'tech2', '123')""")
    con.execute("""INSERT INTO USER (client_id, name, login, password) VALUES ('3', 'оператор2', 'oper2', '123')""")
    con.execute("""INSERT INTO USER (client_id, name, login, password) VALUES ('4', 'технолог3', 'tech3', '123')""")
    con.execute("""INSERT INTO USER (client_id, name, login, password) VALUES ('4', 'оператор3', 'oper3', '123')""")
    con.execute("""INSERT INTO USER (client_id, name, login, password) VALUES ('5', 'технолог4', 'tech4', '123')""")
    con.execute("""INSERT INTO USER (client_id, name, login, password) VALUES ('5', 'оператор4', 'oper4', '123')""")
    
    con.execute("""INSERT INTO FOLDER (client_id, name) VALUES ('1', 'test_DE')""")
    con.execute("""INSERT INTO FOLDER (name, root_folder) VALUES ('DE_sub1', '1')""")
    con.execute("""INSERT INTO FOLDER (name, root_folder) VALUES ('DE_sub2', '1')""")
    con.execute("""INSERT INTO FOLDER (client_id, name) VALUES ('2', 'test_client1')""")
    con.execute("""INSERT INTO FOLDER (name, root_folder) VALUES ('Clt1_sub1', '4')""")
    con.execute("""INSERT INTO FOLDER (name, root_folder) VALUES ('Clt1_sub2', '4')""")
    con.execute("""INSERT INTO FOLDER (client_id, name) VALUES ('3', 'test_client2')""")
    con.execute("""INSERT INTO FOLDER (name, root_folder) VALUES ('Clt2_sub1', '7')""")
    con.execute("""INSERT INTO FOLDER (name, root_folder) VALUES ('Clt2_sub2', '7')""")
    con.execute("""INSERT INTO FOLDER (client_id, name) VALUES ('4', 'test_client3')""")
    con.execute("""INSERT INTO FOLDER (name, root_folder) VALUES ('Clt3_sub1', '10')""")
    con.execute("""INSERT INTO FOLDER (name, root_folder) VALUES ('Clt3_sub2', '10')""")
    con.execute("""INSERT INTO FOLDER (client_id, name) VALUES ('5', 'test_client4')""")
    con.execute("""INSERT INTO FOLDER (name, root_folder) VALUES ('Clt4_sub1', '13')""")
    con.execute("""INSERT INTO FOLDER (name, root_folder) VALUES ('Clt4_sub2', '13')""")
    
    con.execute("""INSERT INTO USER_PERM (user_id, folder_id, rule_id) VALUES ('1', '1', '99')""")
    con.execute("""INSERT INTO USER_PERM (user_id, folder_id, rule_id) VALUES ('1', '4', '99')""")
    con.execute("""INSERT INTO USER_PERM (user_id, folder_id, rule_id) VALUES ('1', '7', '99')""")
    con.execute("""INSERT INTO USER_PERM (user_id, folder_id, rule_id) VALUES ('1', '10', '99')""")
    con.execute("""INSERT INTO USER_PERM (user_id, folder_id, rule_id) VALUES ('1', '13', '99')""")
    con.execute("""INSERT INTO USER_PERM (user_id, folder_id, rule_id) VALUES ('2', '4', '99')""")
    con.execute("""INSERT INTO USER_PERM (user_id, folder_id, rule_id) VALUES ('3', '4', '30')""")
    con.execute("""INSERT INTO USER_PERM (user_id, folder_id, rule_id) VALUES ('3', '4', '30')""")
    con.execute("""INSERT INTO USER_PERM (user_id, folder_id, rule_id) VALUES ('4', '4', '10')""")
    con.execute("""INSERT INTO USER_PERM (user_id, folder_id, rule_id) VALUES ('5', '5', '30')""")
    con.execute("""INSERT INTO USER_PERM (user_id, folder_id, rule_id) VALUES ('6', '5', '10')""")
    con.execute("""INSERT INTO USER_PERM (user_id, folder_id, rule_id) VALUES ('7', '6', '30')""")
    con.execute("""INSERT INTO USER_PERM (user_id, folder_id, rule_id) VALUES ('8', '6', '10')""")
    con.execute("""INSERT INTO USER_PERM (user_id, folder_id, rule_id) VALUES ('9', '7', '30')""")
    con.execute("""INSERT INTO USER_PERM (user_id, folder_id, rule_id) VALUES ('10', '7', '10')""")
    
    
    con.execute("""INSERT INTO DEVICE (folder_id, name_user, IMEI, description, IP, port, modbus_over_tcp, add_pr200, add_tr16, add_inv, type_inv, GMT, enable) 
                VALUES ('2', 'test_device', '1234567890', 'тестовая лебедка', '10.10.100.254', '8899', '1', '10', '16', '1', 'danfoss', '+3', '1')""")
    con.execute("""INSERT INTO DEVICE (folder_id, name_user, IMEI, description, IP, port, modbus_over_tcp, add_pr200, add_tr16, add_inv, type_inv, GMT, enable) 
                VALUES ('2', 'test_device2', '1234567891', 'тестовая лебедка2', '127.0.0.1', '10201', '1', '10', '16', '1', 'danfoss', '+3', '0')""")
    con.execute("""INSERT INTO DEVICE (folder_id, name_user, IMEI, description, IP, port, modbus_over_tcp, add_pr200, add_tr16, add_inv, type_inv, GMT, enable) 
                VALUES ('3', 'test_device3', '1234567892', 'тестовая лебедка3', '127.0.0.1', '10201', '1', '10', '16', '1', 'danfoss', '+3', '0')""")
    con.execute("""INSERT INTO DEVICE (folder_id, name_user, IMEI, description, IP, port, modbus_over_tcp, add_pr200, add_tr16, add_inv, type_inv, GMT, enable) 
                VALUES ('3', 'test_device4', '1234567893', 'тестовая лебедка4', '127.0.0.1', '10203', '1', '10', '16', '1', 'danfoss', '+3', '0')""")
    con.execute("""INSERT INTO DEVICE (folder_id, name_user, IMEI, description, IP, port, modbus_over_tcp, add_pr200, add_tr16, add_inv, type_inv, GMT, enable) 
                VALUES ('5', 'test_device5', '1234567894', 'тестовая лебедка5', '127.0.0.1', '10204', '1', '10', '16', '1', 'danfoss', '+3', '0')""")
    con.execute("""INSERT INTO DEVICE (folder_id, name_user, IMEI, description, IP, port, modbus_over_tcp, add_pr200, add_tr16, add_inv, type_inv, GMT, enable) 
                VALUES ('5', 'test_device6', '1234567895', 'тестовая лебедка6', '127.0.0.1', '10205', '1', '10', '16', '1', 'danfoss', '+3', '0')""")
    con.execute("""INSERT INTO DEVICE (folder_id, name_user, IMEI, description, IP, port, modbus_over_tcp, add_pr200, add_tr16, add_inv, type_inv, GMT, enable) 
                VALUES ('6', 'test_device7', '1234567896', 'тестовая лебедка7', '127.0.0.1', '10206', '1', '10', '16', '1', 'danfoss', '+3', '0')""")
    con.execute("""INSERT INTO DEVICE (folder_id, name_user, IMEI, description, IP, port, modbus_over_tcp, add_pr200, add_tr16, add_inv, type_inv, GMT, enable) 
                VALUES ('6', 'test_device8', '1234567897', 'тестовая лебедка8', '127.0.0.1', '10207', '1', '10', '16', '1', 'danfoss', '+3', '0')""")
    con.execute("""INSERT INTO DEVICE (folder_id, name_user, IMEI, description, IP, port, modbus_over_tcp, add_pr200, add_tr16, add_inv, type_inv, GMT, enable) 
                VALUES ('8', 'test_device9', '1234567898', 'тестовая лебедка9', '127.0.0.1', '10208', '1', '10', '16', '1', 'danfoss', '+3', '0')""")
    con.execute("""INSERT INTO DEVICE (folder_id, name_user, IMEI, description, IP, port, modbus_over_tcp, add_pr200, add_tr16, add_inv, type_inv, GMT, enable) 
                VALUES ('8', 'test_device10', '1234567899', 'тестовая лебедка10', '127.0.0.1', '10209', '1', '10', '16', '1', 'danfoss', '+3', '0')""")
    con.execute("""INSERT INTO DEVICE (folder_id, name_user, IMEI, description, IP, port, modbus_over_tcp, add_pr200, add_tr16, add_inv, type_inv, GMT, enable) 
                VALUES ('9', 'test_device11', '1234567880', 'тестовая лебедка11', '127.0.0.1', '10210', '1', '10', '16', '1', 'danfoss', '+3', '0')""")
    con.execute("""INSERT INTO DEVICE (folder_id, name_user, IMEI, description, IP, port, modbus_over_tcp, add_pr200, add_tr16, add_inv, type_inv, GMT, enable) 
                VALUES ('9', 'test_device12', '1234567881', 'тестовая лебедка12', '127.0.0.1', '10211', '1', '10', '16', '1', 'danfoss', '+3', '0')""")
    con.execute("""INSERT INTO DEVICE (folder_id, name_user, IMEI, description, IP, port, modbus_over_tcp, add_pr200, add_tr16, add_inv, type_inv, GMT, enable) 
                VALUES ('11', 'test_device13', '1234567882', 'тестовая лебедка13', '127.0.0.1', '10212', '1', '10', '16', '1', 'danfoss', '+3', '0')""")
    con.execute("""INSERT INTO DEVICE (folder_id, name_user, IMEI, description, IP, port, modbus_over_tcp, add_pr200, add_tr16, add_inv, type_inv, GMT, enable) 
                VALUES ('11', 'test_device14', '1234567883', 'тестовая лебедка14', '127.0.0.1', '10213', '1', '10', '16', '1', 'danfoss', '+3', '0')""")
    con.execute("""INSERT INTO DEVICE (folder_id, name_user, IMEI, description, IP, port, modbus_over_tcp, add_pr200, add_tr16, add_inv, type_inv, GMT, enable) 
                VALUES ('12', 'test_device15', '1234567884', 'тестовая лебедка15', '127.0.0.1', '10214', '1', '10', '16', '1', 'danfoss', '+3', '0')""")
    con.execute("""INSERT INTO DEVICE (folder_id, name_user, IMEI, description, IP, port, modbus_over_tcp, add_pr200, add_tr16, add_inv, type_inv, GMT, enable) 
                VALUES ('12', 'test_device16', '1234567885', 'тестовая лебедка16', '127.0.0.1', '10215', '1', '10', '16', '1', 'danfoss', '+3', '0')""")
    con.execute("""INSERT INTO DEVICE (folder_id, name_user, IMEI, description, IP, port, modbus_over_tcp, add_pr200, add_tr16, add_inv, type_inv, GMT, enable) 
                VALUES ('14', 'test_device17', '1234567886', 'тестовая лебедка17', '127.0.0.1', '10216', '1', '10', '16', '1', 'danfoss', '+3', '0')""")
    con.execute("""INSERT INTO DEVICE (folder_id, name_user, IMEI, description, IP, port, modbus_over_tcp, add_pr200, add_tr16, add_inv, type_inv, GMT, enable) 
                VALUES ('14', 'test_device18', '1234567887', 'тестовая лебедка18', '127.0.0.1', '10217', '1', '10', '16', '1', 'danfoss', '+3', '0')""")
    con.execute("""INSERT INTO DEVICE (folder_id, name_user, IMEI, description, IP, port, modbus_over_tcp, add_pr200, add_tr16, add_inv, type_inv, GMT, enable) 
                VALUES ('15', 'test_device19', '1234567888', 'тестовая лебедка19', '127.0.0.1', '10218', '1', '10', '16', '1', 'danfoss', '+3', '0')""")
    con.execute("""INSERT INTO DEVICE (folder_id, name_user, IMEI, description, IP, port, modbus_over_tcp, add_pr200, add_tr16, add_inv, type_inv, GMT, enable) 
                VALUES ('15', 'test_device20', '1234567889', 'тестовая лебедка20', '127.0.0.1', '10219', '1', '10', '16', '1', 'danfoss', '+3', '0')""")
    con.execute("""INSERT INTO DEVICE (folder_id, name_user, IMEI, description, IP, port, modbus_over_tcp, add_pr200, add_tr16, add_inv, type_inv, GMT, enable) 
                VALUES ('15', 'test_device21', '1234567870', 'тестовая лебедка21', '127.0.0.1', '10220', '1', '10', '16', '1', 'danfoss', '+3', '0')""")
    con.execute("""INSERT INTO DEVICE (folder_id, name_user, IMEI, description, IP, port, modbus_over_tcp, add_pr200, add_tr16, add_inv, type_inv, GMT, enable) 
                VALUES ('15', 'test_device22', '1234567871', 'тестовая лебедка22', '127.0.0.1', '10221', '1', '10', '16', '1', 'danfoss', '+3', '0')""")
    
    
    
    
    con.commit()