# Generated by Django 5.0.2 on 2024-06-24 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogTimetab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.IntegerField(max_length=10)),
                ('device_id', models.IntegerField(max_length=10)),
                ('timestamp_loc', models.DateTimeField()),
                ('timestamp_dev', models.DateTimeField()),
                ('GMT', models.CharField(max_length=50)),
                ('status', models.IntegerField(max_length=10)),
                ('depth', models.IntegerField(max_length=10)),
                ('power', models.IntegerField(max_length=10)),
                ('status_string', models.IntegerField(max_length=10)),
                ('data', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'LOG_TIME',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogEventtab',
            fields=[
                ('logtimetab_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='charts.logtimetab')),
            ],
            options={
                'db_table': 'LOG_EVENT',
                'managed': False,
            },
            bases=('charts.logtimetab',),
        ),
    ]
