# Generated by Django 5.0.2 on 2024-06-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devicetab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField(max_length=10)),
                ('folder_id', models.IntegerField(max_length=10)),
                ('name_user', models.CharField(max_length=50)),
                ('IMEI', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('IP', models.CharField(max_length=50)),
                ('port', models.IntegerField(max_length=10)),
                ('modbus_over_tcp', models.BooleanField(max_length=10)),
                ('add_pr200', models.IntegerField(max_length=10)),
                ('add_tr16', models.IntegerField(max_length=10)),
                ('add_inv', models.IntegerField(max_length=10)),
                ('type_inv', models.CharField(max_length=50)),
                ('GMT', models.CharField(max_length=50)),
                ('enable', models.BooleanField())
            ],
            options={
                'db_table': 'DEVICE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Foldertab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_id', models.IntegerField(max_length=10)),
                ('client_id', models.IntegerField(max_length=10)),
                ('root_folder', models.IntegerField(max_length=10)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'USER_PERM',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserPermtab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perm_id', models.IntegerField(max_length=10)),
                ('user_id', models.IntegerField(max_length=10)),
                ('folder_id', models.IntegerField(max_length=10)),
                ('rule_id', models.IntegerField(max_length=10)),
            ],
            options={
                'db_table': 'USER_PERM',
                'managed': False,
            },
        ),
    ]
