# Generated by Django 5.0.2 on 2024-06-24 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='foldertab',
            table='FOLDER',
        ),
    ]
