# Generated by Django 5.0.2 on 2024-06-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clienttab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('rule_id', models.IntegerField(max_length=10)),
            ],
            options={
                'db_table': 'CLIENT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rulestab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.IntegerField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('web', models.BooleanField(max_length=10)),
                ('setting', models.BooleanField(max_length=10)),
                ('control', models.BooleanField(max_length=10)),
                ('report', models.BooleanField(max_length=10)),
                ('bot', models.BooleanField(max_length=10)),
            ],
            options={
                'db_table': 'RULES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usertab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=10)),
                ('client_id', models.IntegerField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('tg_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'USER',
                'managed': False,
            },
        ),
    ]
